@hostname = http://localhost:5175

### Get all oblici
GET {{hostname}}/Oblik

### Get oblik by id
GET {{hostname}}/Oblik/62

### Create oblik
POST {{hostname}}/Oblik
Content-Type: application/json

{
  "naziv": "Novi Oblik"
}

### Update oblik
PUT {{hostname}}/Oblik
Content-Type: application/json

{
  "id": 81,
  "naziv": "Izmenjen Oblik"
}

### Delete oblik
DELETE {{hostname}}/Oblik/81
