@hostname = http://localhost:5175

### Get all proizvodjaci
GET {{hostname}}/Proizvodjac

### Get proizvodjac by id
GET {{hostname}}/Proizvodjac/4

### Create proizvodjac
POST {{hostname}}/Proizvodjac
Content-Type: application/json

{
  "naziv": "Novi Proizvodjac",
  "zemlja": "Srbija",
  "telefon": "111222",
  "email": "proizvodjac@email.com"
}

### Update proizvodjac
PUT {{hostname}}/Proizvodjac
Content-Type: application/json

{
  "id": 4,
  "naziv": "Izmenjen Proizvodjac",
  "zemlja": "Nemacka",
  "telefon": "333444",
  "email": "izmenjen@email.com"
}

### Delete proizvodjac
DELETE {{hostname}}/Proizvodjac/4
