@hostname = http://localhost:5175

### Get all employees
GET {{hostname}}/Zaposleni

### Get employee by ID
GET {{hostname}}/Zaposleni/168

### Create a new employee
POST {{hostname}}/Zaposleni
Content-Type: application/json

{
  "Ime": "Pera",
  "Prezime": "Peric",
  "DatumRodj": "1980-01-01T00:00:00",
  "Adresa": "Negde Daleko",
  "Telefon": "065123456",
  "DatumZaposlenja": "2020-01-01T00:00:00",
  "MatBr": "0909009232323"
}

### Update an employee
PUT {{hostname}}/Zaposleni
Content-Type: application/json

{
  "Id": 168,
  "Ime": "Pera",
  "Prezime": "Peric",
  "DatumRodj": "1980-01-01T00:00:00",
  "Adresa": "Negde Daleko 2",
  "Telefon": "065123456",
  "DatumZaposlenja": "2020-01-01T00:00:00",
  "MatBr": "0909009232323"
}

### Delete an employee
DELETE {{hostname}}/Zaposleni/128
